# CUSTOMER CHURN ANALYSES 

-- WITH DEEP LEARNING WE WILL TRY TO ANALYZE WHETHER THERE WILL BE CUSTOMER LOSS OR NOT... 

-- OUR GOAL IS TO FIGURE OUT IF A CUSTOMER WILL LEAVE US BEFORE WE LOSE A CUSTOMER. 

-- FOR EXAMPLE, WE WILL TRY TO FIND OUT IF THE CUSTOMER RENEWS HIS CREDIT CARD EVERY YEAR OR HAS A SUBSCRIPTION, ETC. 

In [1]:
# 1. Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
veriler = pd.read_csv("Churn_Modelling.csv")
veriler.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

# UNDERSTANDING DATA IS IMPORTANT AT THIS POINT 

-- OUR FIRST COLUMN IS THE INDEX, I.E. THE NUMBER OF NORMAL LINES, A FEATURE OF THE PANDAS LIBRARY ITSELF 

-- ROWNUMBER : A UNIQUE VALUE IS GIVEN, EACH LINE IS NUMBERED, THAT IS, WE CAN THINK OF IT AS AN INDEX LINE, IT DOES NOT CONTRIBUTE ANYTHING TO US... IT DOESN'T MAKE ANY SENSE FOR US. THESE LINES CAUSE VERY HARMFUL THINGS LIKE MEMORIZATION...!!!!

-- CUSTOMERID : THINK LIKE A TC ID NUMBER, AGAIN UNIQUE DOES NOT GIVE US ANY INFORMATION, IT CAUSES MEMORIZATION 

-- SURNAME : AGAIN THE SAME DOES NOT HAVE ANY EFFECT 

NOTE : FIRST 3 COLUMNS ARE CLEANED 

-- OTHER COLUMNS MAY HAVE SOMETHING TO DO WITH PREDICTION 

-- THE EXITED COLUMN IS WHETHER THE CUSTOMER HAS LEFT US OR NOT, WE ARE TRYING TO PREDICT THIS 

In [3]:
X = veriler.iloc[:,3:13].values
Y = veriler.iloc[:,13].values

In [4]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [5]:
Y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [6]:
from sklearn import preprocessing 

In [7]:
le=preprocessing.LabelEncoder()
X[:,1] = le.fit_transform(X[:,1]) #Geopraphy

le2=preprocessing.LabelEncoder()
X[:,2] = le2.fit_transform(X[:,2]) #gender 

In [8]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [9]:
ohe = ColumnTransformer(transformers=[("ohe", OneHotEncoder(dtype=float), [1])],
                        remainder="passthrough")
X = ohe.fit_transform(X)

X = X[:,1:] 

In [10]:
X

array([[0.0, 0.0, 619, ..., 1, 1, 101348.88],
       [0.0, 1.0, 608, ..., 0, 1, 112542.58],
       [0.0, 0.0, 502, ..., 1, 0, 113931.57],
       ...,
       [0.0, 0.0, 709, ..., 0, 1, 42085.58],
       [1.0, 0.0, 772, ..., 1, 0, 92888.52],
       [0.0, 0.0, 792, ..., 1, 0, 38190.78]], dtype=object)

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.33,random_state=0)

In [12]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [13]:
X_train=sc.fit_transform(x_train)
X_test=sc.fit_transform(x_test)

In [14]:
X_train

array([[-0.56953701, -0.57436296, -1.78451879, ..., -1.56299709,
        -1.03339307,  1.0890591 ],
       [-0.56953701, -0.57436296,  1.47401668, ...,  0.63979645,
         0.967686  , -0.4551902 ],
       [-0.56953701, -0.57436296, -0.82854466, ..., -1.56299709,
         0.967686  , -0.65446947],
       ...,
       [-0.56953701, -0.57436296,  0.89837634, ...,  0.63979645,
        -1.03339307,  1.40745917],
       [-0.56953701,  1.74105933, -0.62295883, ...,  0.63979645,
         0.967686  ,  0.83939459],
       [ 1.75581215, -0.57436296, -0.2837422 , ...,  0.63979645,
        -1.03339307,  0.31973777]])

# WE'VE PROCESSED THE DATA SO FAR. 

# DEEP LEARNING

In [15]:
# ARTIFICIAL NEURAL NETWORK 

import keras 

-- now after installing the keras 2 things are important 

-- first model identification 

-- second is layers 

-- we will use the Sequential Model... THIS IS A STRUCTURE USED TO DESCRIBE THE ARTIFICIAL NEURAL NETWORK 

NOTE : WITH THIS MODEL WE TELL KERAS TO CREATE AN ARTIFICIAL NEURAL NETWORK  

In [16]:
from keras.models import Sequential
from keras.layers import Dense # it contains the object from which we can create neurons!!!

In [17]:
#  we will use it as a classification algorithm 

classifier = Sequential() # here we have created an artificial neural network 

In [18]:
# We will create our artificial neural network by modifying the classifier. 
# Look by checking the layers while creating the artificial neural network on keras site.  
classifier.add(Dense(6,kernel_initializer = "uniform",activation = "relu",input_dim = 11)) # can be averaged over the input layer and output layer, but this is not exact 
# 6 hidden layer neurons 
# You can also find the activation function on the keras site 
# input_dim number of input data 
# 6 hidden layers 11 input layers 
# the classifier will try to find the optimum value by changing what we define here 

In [19]:
# let's add a hidden layer 
classifier.add(Dense(6,kernel_initializer = "uniform",activation = "relu"))

In [20]:
# let's look at the output layer 
classifier.add(Dense(1,kernel_initializer = "uniform",activation = "sigmoid"))
# currently neural network is complete

In [21]:
help(classifier.compile)

Help on method compile in module keras.src.engine.training:

compile(optimizer='rmsprop', loss=None, metrics=None, loss_weights=None, weighted_metrics=None, run_eagerly=None, steps_per_execution=None, jit_compile=None, pss_evaluation_shards=0, **kwargs) method of keras.src.engine.sequential.Sequential instance
    Configures the model for training.
    
    Example:
    
    ```python
    model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
                  loss=tf.keras.losses.BinaryCrossentropy(),
                  metrics=[tf.keras.metrics.BinaryAccuracy(),
                           tf.keras.metrics.FalseNegatives()])
    ```
    
    Args:
        optimizer: String (name of optimizer) or optimizer instance. See
          `tf.keras.optimizers`.
        loss: Loss function. May be a string (name of loss function), or
          a `tf.keras.losses.Loss` instance. See `tf.keras.losses`. A loss
          function is any callable with the signature `loss = fn(y_true,
  

In [22]:
classifier.compile(optimizer = 'adam',loss="binary_crossentropy",metrics=['accuracy'])
# We set the synapses here, we did it by looking at keras. 
# explains how to optimize the values on synapses 
# the algorithm we use is sgd 
# we will make loss = binary because ultimately it will be estimated binary 
# we choose it according to the data to be estimated 

In [23]:
help(classifier.fit)

Help on method fit in module keras.src.engine.training:

fit(x=None, y=None, batch_size=None, epochs=1, verbose='auto', callbacks=None, validation_split=0.0, validation_data=None, shuffle=True, class_weight=None, sample_weight=None, initial_epoch=0, steps_per_epoch=None, validation_steps=None, validation_batch_size=None, validation_freq=1, max_queue_size=10, workers=1, use_multiprocessing=False) method of keras.src.engine.sequential.Sequential instance
    Trains the model for a fixed number of epochs (dataset iterations).
    
    Args:
        x: Input data. It could be:
          - A Numpy array (or array-like), or a list of arrays
            (in case the model has multiple inputs).
          - A TensorFlow tensor, or a list of tensors
            (in case the model has multiple inputs).
          - A dict mapping input names to the corresponding array/tensors,
            if the model has named inputs.
          - A `tf.data` dataset. Should return a tuple
            of either `(

In [24]:
classifier.fit(X_train,y_train , epochs = 50)

Epoch 1/50
210/210 [==============================] - 5s 6ms/step - loss: 0.5933 - accuracy: 0.7964
Epoch 2/50
210/210 [==============================] - 1s 4ms/step - loss: 0.4394 - accuracy: 0.7979
Epoch 3/50
210/210 [==============================] - 1s 4ms/step - loss: 0.4256 - accuracy: 0.7981
Epoch 4/50
210/210 [==============================] - 2s 8ms/step - loss: 0.4217 - accuracy: 0.8139
Epoch 5/50
210/210 [==============================] - 2s 7ms/step - loss: 0.4190 - accuracy: 0.8209
Epoch 6/50
210/210 [==============================] - 1s 7ms/step - loss: 0.4161 - accuracy: 0.8227
Epoch 7/50
210/210 [==============================] - 2s 8ms/step - loss: 0.4139 - accuracy: 0.8255
Epoch 8/50
210/210 [==============================] - 1s 6ms/step - loss: 0.4119 - accuracy: 0.8284
Epoch 9/50
210/210 [==============================] - 1s 4ms/step - loss: 0.4095 - accuracy: 0.8276
Epoch 10/50
210/210 [==============================] - 1s 4ms/step - loss: 0.4080 - accuracy: 0.8321

In [25]:
y_pred = classifier.predict(X_test)

104/104 [==============================] - 1s 4ms/step


In [26]:
y_pred

array([[0.26284087],
       [0.26818398],
       [0.14592002],
       ...,
       [0.20102702],
       [0.51384485],
       [0.01964978]], dtype=float32)

In [27]:
y_pred = (y_pred>0.5)

In [28]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)

print(cm)

[[2546   71]
 [ 449  234]]
